name: Run on issue
on: issues
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Issue description
        run: 'echo "Action: ${{github.event.action}}, Title: ${{github.event.issue.title}}, Name: ${{github.event.issue.user.login}}"'
