name: Run on issue
on: issues
jobs:
  on_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Issue description
        run: 'echo "Action: ${{github.event.action}}, Title: ${{github.event.issue.title}}, Name: ${{github.event.issue.user.login}}"'
  auto_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Reply to the person
        uses: actions/github-script@v7
        with:
          script: |
            const user = context.payload.issue.user.login;
            const time = context.payload.issue.created_at;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Dzięki za zgłoszenie, @${user}! Zgłoszono o @${time}. Zajmiemy się tym!`
            })
